---
kind: pipeline
name: durl
clone:
  depth: 1
steps:
- name: durl
  image: quay.io/suzuki_shunsuke/durl:1.0.0
  commands:
  - sh scripts/durl.sh
---
kind: pipeline
name: shell scripts
clone:
  depth: 1
steps:
- name: shellcheck
  image: koalaman/shellcheck-alpine:v0.7.1
  commands:
  - shellcheck scripts/* githooks/*
- name: shfmt
  image: mvdan/shfmt:v3.1.2-alpine
  commands:
  - shfmt -d .
---
kind: pipeline
name: yamllint
steps:
- name: yamllint
  image: quay.io/suzuki_shunsuke/yamllint:1.23.0
  commands:
  - 'find . \( -name "*.yml" -o -name "*.yaml" \) -print0 | xargs -0 yamllint -c .yamllint.yml'
---
kind: pipeline
name: build
clone:
  depth: 1
volumes:
- name: gopath
  temp: {}
steps:
- name: download go modules
  image: golang:1.15.1
  commands:
  - go mod download
  volumes: &volumes
  - name: gopath
    path: /go
- name: golangci-lint
  image: golangci/golangci-lint:v1.30.0-alpine
  commands:
  - golangci-lint run
  volumes: *volumes
- name: test
  image: golang:1.15.1
  commands:
  # bash and cgo seem to be required
  - bash ci/test.sh "$DRONE_REPO_NAME"
  environment:
    CC_TEST_REPORTER_ID:
      from_secret: cc_test_reporter_id
  volumes: *volumes
