---
linters:
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofmt
  - goimports
  - golint
  - gosimple
  - govet
  - interfacer
  - maligned
  - misspell
  - nakedret
  - staticcheck
  - structcheck
  - unconvert
  - unused
  - varcheck
  disable-all: true
